name: Paywall
options:
  bundleIdentifer: me.superwall
packages:
  ASN1Swift:
    url: https://github.com/tikhop/ASN1Swift
    from: 1.2.4

targets:
  Paywall:
    scheme:
      testTargets:
        - PaywallTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.superwall.Paywall"
    info:
      path: Paywall.xcodeproj/Paywall_Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "FMWK"
        CFBundleShortVersionString: "1.0"
        CFBundleSignature: ????
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSPrincipalClass: ""
    type: framework
    platform: iOS
    deploymentTarget: "11.2"
    sources: [Sources/]
    dependencies:
      - package: ASN1Swift
  PaywallTests:
    scheme: {}
    sources: [Tests/]
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: Paywall
      - package: ASN1Swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.superwall.PaywallTests"
    info:
      path: Paywall.xcodeproj/PaywallTests_Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "FMWK"
        CFBundleShortVersionString: "1.0"
        CFBundleSignature: ????
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSPrincipalClass: ""

  #Paywall_Paywall:
  #   type: bundle
  #  platform: iOS
  #  deploymentTarget: "11.2"
  # sources: [Sources/Paywall/Assets.xcassets]
