name: superwall
options:
  bundleIdentifer: com.superwall
packages:
  ASN1Swift:
    url: https://github.com/tikhop/ASN1Swift
    from: 1.2.4

targets:
  Superwall:
    scheme:
      testTargets:
        - superwallTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.superwall.Superwall"
    info:
      path: Superwall.xcodeproj/Superwall_Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "FMWK"
        CFBundleShortVersionString: "1.0"
        CFBundleSignature: ????
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSPrincipalClass: ""
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Sources/]
    dependencies:
      - package: ASN1Swift
  SuperwallTests:
    scheme: {}
    sources: [Tests/]
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: Superwall
      - package: ASN1Swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.superwall.SuperwallTests"
    info:
      path: Superwall.xcodeproj/SuperwallTests_Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "FMWK"
        CFBundleShortVersionString: "1.0"
        CFBundleSignature: ????
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSPrincipalClass: ""
