name: Build Documentation

on:
  push:
    #branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: macos-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Build Doc Bundle 📗
        run: |
          echo "🚀 Starting to build documentation"
          swift package generate-xcodeproj
          xcodebuild -version
          xcodebuild docbuild -scheme Paywall-Package -derivedDataPath ./docbuild -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 Pro'
      - name: Push new documentation to docs folder ⬆️
        run: |
          DOCC_DIR=`find ./docbuild -type d -iname "Paywall.doccarchive"`
          # we get the last commit message for this library and add current date
          echo "$DOCC_DIR"
          $(xcrun --find docc) process-archive transform-for-static-hosting "$DOCC_DIR" --output-path ./webdocs --hosting-base-path sdk.superwall.me

          sudo git config --global user.name 'Jake'
          sudo git config --global user.email 'jakemor@users.noreply.github.com'
          git fetch --all
          git checkout --track origin/gh-pages
          sudo cp -r ./webdocs docs/
          sudo git add -A docs/
          sudo git commit -m "Generated Docs"
          sudo git push
