name: Build Documentation

on:
  push:
    #branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: macos-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Cache DocC
        uses: actions/cache@v3
        env:
          cache-name: cache-docc
        with:
          path: swift-docc
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install DocC Renderer
        run: |
          git clone https://github.com/apple/swift-docc-render.git
          ls ${{ github.workspace }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: swift-docc-render/package-lock.json
      - name: Install DocC Renderer
        run: |
          ls ${{ github.workspace }}
          cd swift-docc-render
          npm install
          cd ..
          echo "DOCC_HTML_DIR=${GITHUB_WORKSPACE}/swift-docc-render >> $GITHUB_ENV
          echo "$DOCC_HTML_DIR"
      - name: Install DocC
        run: |
          git clone https://github.com/apple/swift-docc.git
          cd swift-docc
          swift build
          swift run docc --help
          cd ..
      - name: xcodegen
        uses: xavierLowmiller/xcodegen-action@1.1.2
      - name: Build Doc Bundle 📗
        run: |
          echo "🚀 Starting to build documentation"
          xcodebuild docbuild -scheme Paywall -derivedDataPath ./docbuild -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 Pro'
      - name: Push new documentation to docs folder ⬆️
        run: |
          # we get the last commit message for this library and add current date
          cd swift-docc
          swift run docc process-archive transform-for-static-hosting ../docbuild/Build/Products/Debug-iphonesimulator/Paywall.doccarchive --output-path ../web
          cd ..
          sudo git config --global user.name 'Jake'
          sudo git config --global user.email 'jakemor@users.noreply.github.com'
          git fetch --all
          git checkout --track origin/gh-pages
          sudo cp -r ./web docs/
          sudo git add -A docs/
          sudo git commit -m "Generated Docs"
          sudo git push
