name: Dispatch UI Tests

on:
  push:
    paths:
      - '!Examples/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger repository_dispatch event
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.UI_TESTS_REPO_ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        "https://api.github.com/repos/superwall-me/Superwall-iOS-UI-tests/dispatches" \
        -d '{"event_type": "branch-push", "client_payload": {"ref": "${{ github.ref }}", "commit": "${{ github.sha }}"}}'
