name: Dispatch UI Tests

on:
  push:
    branches:
      - develop

jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger repository_dispatch event
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.UI_TESTS_REPO_ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        "https://api.github.com/repos/superwall-me/Superwall-iOS-UI-tests/dispatches" \
        -d '{"event_type": "branch-push", "client_payload": {"ref": "${{ github.ref }}", "commit": "${{ github.sha }}", "author": "${{ github.event.head_commit.author.name }}" }}'
