name: TagVersion

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2        
    - name: Tag
      run: | 
          sudo git config --global user.name 'Jake'
          sudo git config --global user.email 'jakemor@users.noreply.github.com'
          sudo git pull
          echo "\n\n\n- - - - - VERSION - - - - -\n\n\n"
          sed -n 21p ./Sources/SuperwallKit/Misc/Constants.swift
          echo "\n\n\n- - - - - END VERSION - - - - -\n\n\n"
          sudo git tag -a $(sed -n 21p ./Sources/SuperwallKit/Misc/Constants.swift) -m "tags with latest version"
          sudo git push --tags || true
          sudo git checkout -b release/$(sed -n 21p ./Sources/SuperwallKit/Misc/Constants.swift)
          sudo git push -u origin release/$(sed -n 21p ./Sources/SuperwallKit/Misc/Constants.swift)

  cocoapods:
    needs: tag
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push SuperwallKit.podspec --allow-warnings
