name: TagVersion

on:
  push:
    branches: [ jake/sw-183-add-x-sdk-version-to-headers-on-all ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: | 
          sudo git config --global user.name 'Jake'
          sudo git config --global user.email 'jakemor@users.noreply.github.com'
          git pull
          echo "\n\n\n- - - - - VERSION - - - - -\n\n\n"
          sed -n 21p ./Sources/Paywall/Misc/Constants.swift
          echo "\n\n\n- - - - - END VERSION - - - - -\n\n\n"
          VER=$(sed -n 21p ./Sources/Paywall/Misc/Constants.swift)
          echo "SDK_VERSION=$VER" >> $GITHUB_ENV
          echo "the version is: ${{ env.SDK_VERSION }}"

